default_language_version:
    python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.29.3
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.24.0
  hooks:
  - id: markdownlint