version: "3.8"
services:
  cpu-ml-nbserver:
    image: mlcpu
    init: true
    build:
      context: ./
      dockerfile: cpu/mlcpu.Dockerfile
    env_file: ./.env
    ports:
      - ${JUPYTER_PORT_ML}:${JUPYTER_PORT_ML}
    volumes:
      - ${ROOT_DIR}:/jupyter
      - ${DATA_DIR}:/data
    ipc: "host"
    command:
      [
        "jupyter",
        "notebook",
        "--ip=*",
        "--port=${JUPYTER_PORT_ML}",
        "--allow-root",
        "--notebook-dir=${JUPYTER_DIR}",
        "--NotebookApp.token=${JUPYTER_TOKEN}",
      ]
  cpu-ml-trainingserver:
    image: mlcpu
    init: true
    build:
      context: ./
      dockerfile: cpu/mlcpu.Dockerfile
    env_file: ./.env
    ports:
      - ${JUPYTER_PORT_ML}:${JUPYTER_PORT_ML}
    volumes:
      - ${ROOT_DIR}:/jupyter
      - ${DATA_DIR}:/data
    ipc: "host"
    command:
      [
        "python",
        "train.py",
      ]